name: educational_kids_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  contained_tab_bar_view: ^0.8.0
  fluentui_system_icons: ^1.1.252
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
